const SET_LOADING = "SET_LOADING";
const SET_TERM = "SET_TERM";
const SET_NEWS = "SET_NEWS";
const REMOVE_NEWS = "REMOVE_NEWS";
const SET_NO_OF_PAGES = "SET_NO_OF_PAGES";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const NEXT_PAGE = "NEXT_PAGE";
const PREV_PAGE = "PREV_PAGE";

export {
  NEXT_PAGE,
  PREV_PAGE,
  SET_LOADING,
  SET_NEWS,
  SET_TERM,
  REMOVE_NEWS,
  SET_NO_OF_PAGES,
  SET_CURRENT_PAGE,
};
